<?php
return [
    [
        'id' => 1,
        'name' => 'Electronics',
        'photo' => 'images/category/electronic.png',
    ],
    [   'id' => 2,
        'name' => 'Clothing',
        'photo' => 'images/category/clothing.png',
    ],
    [   'id' => 3,
        'name' => 'Books',
        'photo' => 'images/category/book.png',
    ],
    [   'id' => 4,
        'name' => 'Home & Kitchen',
        'photo' => 'images/category/homeandkitchen.png',
    ],
    [   'id' => 5,
        'name' => 'Sports',
        'photo' => 'images/category/sport.png',
    ],
    [   'id' => 6,
        'name' => 'Health Care',
        'photo' => 'images/category/health.png',
    ],
    [   'id' => 7,
        'name' => 'Toys & Games',
        'photo' => 'images/category/toyandgame.png',
    ],
    [   'id' => 8,
        'name' => 'Beauty',
        'photo' => 'images/category/beauty.png',
    ],
    [   'id' => 9,
        'name' => 'Automotive',
        'photo' => 'images/category/automotive.png',
    ],
    [   'id' => 10,
        'name' => 'Grocery',
        'photo' => 'images/category/grocery.png',
    ],
];
