<?php
return [
    [
        'codeno' => 'P0001',
        'name' => 'Iphone 11',
        'photo' => ["images/item/iphone11.png","images/item/iphone11-1.png"],
        'price' => 999.99,
        'discount' => 10,
        'description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
        'subcategory_id' => 4,
        'brand_id' => 1,
    ],
    [
        'codeno' => 'P0002',
        'name' => 'Dell Laptop',
        'photo' => ["images/item/dell.png","images/item/dell 1.png"],
        'price' => 1499.99,
        'discount' => 20,
        'description' => 'Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
        'subcategory_id' => 1,
        'brand_id' => 13,
    ],
    [
        'codeno' => 'P0003',
        'name' => 'Sony Camera',
        'photo' => ["images/item/sony.png","images/item/sony 1.png"],
        'price' => 599.99,
        'discount' => 15,
        'description' => 'Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
        'subcategory_id' => 3,
        'brand_id' => 14,
    ],
    [
        'codeno' => 'P0004',
        'name' => 'Smartwatch',
        'photo' => ["images/item/smartwatch.png","images/item/smartwatch 1.png"],
        'price' => 199.99,
        'discount' => 5,
        'description' => 'Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.',
        'subcategory_id' => 4,
        'brand_id' => 4,
    ],
    [
        'codeno' => 'P0005',
        'name' => 'Wireless Headphones',
        'photo' => ["images/item/headphone.png","images/item/headphone 1.png"],
        'price' => 79.99,
        'discount' => 8,
        'description' => 'Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
        'subcategory_id' => 2,
        'brand_id' => 3,
    ],
    [
        'codeno' => 'P0006',
        'name' => 'Tablet',
        'photo' => ["images/item/tablet.png","images/item/tablet 1.png"],
        'price' => 299.99,
        'discount' => 12,
        'description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
        'subcategory_id' => 4,
        'brand_id' => 1,
    ],
    [
        'codeno' => 'P0007',
        'name' => 'Fitness Tracker',
        'photo' => ["images/item/fitnesstracker.png","images/item/fitnesstracker 1.png"],
        'price' => 49.99,
        'discount' => 0,
        'description' => 'Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium.',
        'subcategory_id' => 24,
        'brand_id' => 1,
    ],
    [
        'codeno' => 'P0008',
        'name' => 'Gaming Console',
        'photo' => ["images/item/gamingconsole.jpeg"],
        'price' => 399.99,
        'discount' => 25,
        'description' => 'Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt.',
        'subcategory_id' => 5,
        'brand_id' => 2,
    ],
    [
        'codeno' => 'P0009',
        'name' => 'Cotton knit Hoodies',
        'photo' => ["images/item/hoodie.jpeg","images/item/hoodie 1.avif"],
        'price' => 99.99,
        'discount' => 15,
        'description' => 'Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem.',
        'subcategory_id' => 6,
        'brand_id' => 6,
    ],
    [
        'codeno' => 'P0010',
        'name' => 'Polos Shirt',
        'photo' => ["images/item/polo.webp","images/item/polo 1.png"],
        'price' => 249.99,
        'discount' => 18,
        'description' => 'Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur.',
        'subcategory_id' => 7,
        'brand_id' => 7,
    ],
    [
        'codeno' => 'P0011',
        'name' => 'Pullover Sweater',
        'photo' => 'https://via.placeholder.com/640x480?text=Digital+Camera+H',
        'price' => 399.99,
        'discount' => 20,
        'description' => 'At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate non provident.',
        'subcategory_id' => 9,
        'brand_id' => 7,
    ],
    [
        'codeno' => 'P0012',
        'name' => 'Mock Neck Sweater',
        'photo' => 'https://via.placeholder.com/640x480?text=Wireless+Mouse+I',
        'price' => 29.99,
        'discount' => 0,
        'description' => 'Et harum quidem rerum facilis est et expedita distinctio.',
        'subcategory_id' => 9,
        'brand_id' => 6,
    ],
    [
        'codeno' => 'P0013',
        'name' => 'Alexander Hamilton',
        'photo' => 'https://via.placeholder.com/640x480?text=Portable+Hard+Drive+J',
        'price' => 119.99,
        'discount' => 10,
        'description' => 'Nam libero tempore, cum soluta nobis est eligendi optio cumque nihil impedit quo minus id quod maxime placeat facere possimus, omnis voluptas assumenda est, omnis dolor repellendus.',
        'subcategory_id' => 13,
        'brand_id' => 15,
    ],
    [
        'codeno' => 'P0014',
        'name' => 'Steve Jobs',
        'photo' => 'https://via.placeholder.com/640x480?text=Wireless+Keyboard+K',
        'price' => 49.99,
        'discount' => 5,
        'description' => 'Temporibus autem quibusdam et aut officiis debitis aut rerum necessitatibus saepe eveniet ut et voluptates repudiandae sint et molestiae non recusandae.',
        'subcategory_id' => 13,
        'brand_id' => 15,
    ],
    [
        'codeno' => 'P0015',
        'name' => 'Bullfrog',
        'photo' => 'https://via.placeholder.com/640x480?text=Fitness+Watch+L',
        'price' => 79.99,
        'discount' => 0,
        'description' => 'Itaque earum rerum hic tenetur a sapiente delectus, ut aut reiciendis voluptatibus maiores alias consequatur aut perferendis doloribus asperiores repellat.',
        'subcategory_id' => 18,
        'brand_id' => 16,
    ],
    [
        'codeno' => 'P0016',
        'name' => 'Badminton - Racquet',
        'photo' => 'https://via.placeholder.com/640x480?text=E-book+Reader+M',
        'price' => 129.99,
        'discount' => 10,
        'description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
        'subcategory_id' => 21,
        'brand_id' => 14,
    ],
    [
        'codeno' => 'P0017',
        'name' => 'Exercise Bike',
        'photo' => 'https://via.placeholder.com/640x480?text=Bluetooth+Earbuds+N',
        'price' => 69.99,
        'discount' => 0,
        'description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
        'subcategory_id' => 24,
        'brand_id' => 1,
    ],
];