<?php
return [
    [
        'codeno' => 'P0001',
        'name' => 'Iphone 11',
        'photo' => 'https://via.placeholder.com/640x480?text=Iphone11',
        'price' => 999.99,
        'discount' => 10,
        'description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
        'subcategory_id' => 4,
        'brand_id' => 1,
    ],
    [
        'codeno' => 'P0002',
        'name' => 'Dell Laptop',
        'photo' => 'https://via.placeholder.com/640x480?text=Dell+Laptop',
        'price' => 1499.99,
        'discount' => 20,
        'description' => 'Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
        'subcategory_id' => 1,
        'brand_id' => 13,
    ],
    [
        'codeno' => 'P0003',
        'name' => 'Sony Camera',
        'photo' => 'https://via.placeholder.com/640x480?text=Sony Camera',
        'price' => 599.99,
        'discount' => 15,
        'description' => 'Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
        'subcategory_id' => 3,
        'brand_id' => 14,
    ],
    [
        'codeno' => 'P0004',
        'name' => 'Smartwatch',
        'photo' => 'https://via.placeholder.com/640x480?text=Smartwatch+A',
        'price' => 199.99,
        'discount' => 5,
        'description' => 'Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.',
        'subcategory_id' => 4,
        'brand_id' => 4,
    ],
    [
        'codeno' => 'P0005',
        'name' => 'Wireless Headphones',
        'photo' => 'https://via.placeholder.com/640x480?text=Wireless+Headphones+B',
        'price' => 79.99,
        'discount' => 8,
        'description' => 'Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
        'subcategory_id' => 2,
        'brand_id' => 3,
    ],
    [
        'codeno' => 'P0006',
        'name' => 'Tablet',
        'photo' => 'https://via.placeholder.com/640x480?text=Tablet+C',
        'price' => 299.99,
        'discount' => 12,
        'description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
        'subcategory_id' => 4,
        'brand_id' => 1,
    ],
    [
        'codeno' => 'P0007',
        'name' => 'Fitness Tracker',
        'photo' => 'https://via.placeholder.com/640x480?text=Fitness+Tracker+D',
        'price' => 49.99,
        'discount' => 0,
        'description' => 'Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium.',
        'subcategory_id' => 24,
        'brand_id' => 1,
    ],
    [
        'codeno' => 'P0008',
        'name' => 'Gaming Console',
        'photo' => 'https://via.placeholder.com/640x480?text=Gaming+Console+E',
        'price' => 399.99,
        'discount' => 25,
        'description' => 'Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt.',
    ],
    [
        'codeno' => 'P0009',
        'name' => 'Bluetooth Speaker F',
        'photo' => 'https://via.placeholder.com/640x480?text=Bluetooth+Speaker+F',
        'price' => 99.99,
        'discount' => 15,
        'description' => 'Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem.',
    ],
    [
        'codeno' => 'P0010',
        'name' => 'VR Headset G',
        'photo' => 'https://via.placeholder.com/640x480?text=VR+Headset+G',
        'price' => 249.99,
        'discount' => 18,
        'description' => 'Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur.',
    ],
    [
        'codeno' => 'P0011',
        'name' => 'Digital Camera H',
        'photo' => 'https://via.placeholder.com/640x480?text=Digital+Camera+H',
        'price' => 399.99,
        'discount' => 20,
        'description' => 'At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate non provident.',
    ],
    [
        'codeno' => 'P0012',
        'name' => 'Wireless Mouse I',
        'photo' => 'https://via.placeholder.com/640x480?text=Wireless+Mouse+I',
        'price' => 29.99,
        'discount' => 0,
        'description' => 'Et harum quidem rerum facilis est et expedita distinctio.',
    ],
    [
        'codeno' => 'P0013',
        'name' => 'Portable Hard Drive J',
        'photo' => 'https://via.placeholder.com/640x480?text=Portable+Hard+Drive+J',
        'price' => 119.99,
        'discount' => 10,
        'description' => 'Nam libero tempore, cum soluta nobis est eligendi optio cumque nihil impedit quo minus id quod maxime placeat facere possimus, omnis voluptas assumenda est, omnis dolor repellendus.',
    ],
    [
        'codeno' => 'P0014',
        'name' => 'Wireless Keyboard K',
        'photo' => 'https://via.placeholder.com/640x480?text=Wireless+Keyboard+K',
        'price' => 49.99,
        'discount' => 5,
        'description' => 'Temporibus autem quibusdam et aut officiis debitis aut rerum necessitatibus saepe eveniet ut et voluptates repudiandae sint et molestiae non recusandae.',
    ],
    [
        'codeno' => 'P0015',
        'name' => 'Fitness Watch L',
        'photo' => 'https://via.placeholder.com/640x480?text=Fitness+Watch+L',
        'price' => 79.99,
        'discount' => 0,
        'description' => 'Itaque earum rerum hic tenetur a sapiente delectus, ut aut reiciendis voluptatibus maiores alias consequatur aut perferendis doloribus asperiores repellat.',
    ],
    [
        'codeno' => 'P0016',
        'name' => 'E-book Reader M',
        'photo' => 'https://via.placeholder.com/640x480?text=E-book+Reader+M',
        'price' => 129.99,
        'discount' => 10,
        'description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    ],
    [
        'codeno' => 'P0017',
        'name' => 'Bluetooth Earbuds N',
        'photo' => 'https://via.placeholder.com/640x480?text=Bluetooth+Earbuds+N',
        'price' => 69.99,
        'discount' => 0,
        'description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    ],
];