<?php
return [
    ['name' => 'Laptops','category_id' => 1],
    ['name' => 'Headphones','category_id' => 1],
    ['name' => 'Cameras','category_id' => 1],
    ['name' => 'Smartphones','category_id' => 1],
    ['name' => 'Monitors','category_id' => 1],
    ['name' => 'Hoodies','category_id' => 2],
    ['name' => 'T-shirts','category_id' => 2],
    ['name' => 'Jeans','category_id' => 2],
    ['name' => 'Sweaters','category_id' => 2],
    ['name' => 'Fiction','category_id' => 3],
    ['name' => 'Non-fiction','category_id' => 3],
    ['name' => 'Myster','category_id' => 3],
    ['name' => 'Biography ','category_id' => 3],
    ['name' => 'Thriller','category_id' => 3],
    ['name' => 'Kitchen Appliances','category_id' => 4],
    ['name' => 'Cookware ','category_id' => 4],
    ['name' => 'Home Décor','category_id' => 4],
    ['name' => 'Furniture','category_id' => 4],
    ['name' => 'Bedding','category_id' => 4],
    ['name' => 'Outdoor Sports','category_id' => 5],
    ['name' => 'Indoor Sports','category_id' => 5],
    ['name' => 'Team Sports','category_id' => 5],
    ['name' => 'Individual Sports','category_id' => 5],
    ['name' => 'Fitness','category_id' => 5],
    ['name' => 'Self-help','category_id' => 6],

];