<?php
return [
    ['id' => 1,'name' => 'Laptops','category_id' => 1],
    ['id' => 2,'name' => 'Headphones','category_id' => 1],
    ['id' => 3,'name' => 'Cameras','category_id' => 1],
    ['id' => 4,'name' => 'Smartphones','category_id' => 1],
    ['id' => 5,'name' => 'Monitors','category_id' => 1],
    ['id' => 6,'name' => 'Hoodies','category_id' => 2],
    ['id' => 7,'name' => 'T-shirts','category_id' => 2],
    ['id' => 8,'name' => 'Jeans','category_id' => 2],
    ['id' => 9,'name' => 'Sweaters','category_id' => 2],
    ['id' => 10,'name' => 'Fiction','category_id' => 3],
    ['id' => 11,'name' => 'Non-fiction','category_id' => 3],
    ['id' => 12,'name' => 'Myster','category_id' => 3],
    ['id' => 13,'name' => 'Biography ','category_id' => 3],
    ['id' => 14,'name' => 'Thriller','category_id' => 3],
    ['id' => 15,'name' => 'Kitchen Appliances','category_id' => 4],
    ['id' => 16,'name' => 'Cookware ','category_id' => 4],
    ['id' => 17,'name' => 'Home Décor','category_id' => 4],
    ['id' => 18,'name' => 'Furniture','category_id' => 4],
    ['id' => 19,'name' => 'Bedding','category_id' => 4],
    ['id' => 20,'name' => 'Outdoor Sports','category_id' => 5],
    ['id' => 21,'name' => 'Indoor Sports','category_id' => 5],
    ['id' => 22,'name' => 'Team Sports','category_id' => 5],
    ['id' => 23,'name' => 'Individual Sports','category_id' => 5],
    ['id' => 24,'name' => 'Fitness','category_id' => 5],
    ['id' => 25,'name' => 'Self-help','category_id' => 6],

];